### ISSUE TITLE
Failure to import a .gls file

### ISSUE THREAD

**Issue by alastairdb** [chickendude/Natibo#16]
Is the any description of the format of a `.gls` file?

I tried to guess the format and to import my test files into v0.2.4-beta on my phone (an Honor 6X running Android 7.0) but I failed. In the input dialogue, I could see my files with a `.gls` extension in my Download directory but they were not selectable. Where did I go wrong?

**Comment by jubalh** [comment]
AFAIK the README mentions the tool which creates the `.gls` file. Here it is: https://github.com/chickendude/GlossikaNativeGLS

**Comment by alastairdb** [comment]
That tool does not quite work for me. With a bit of tweaking, I managed to split the mp3's correctly. As for the pdf's, I have managed to extract the text via OCR and I tried to mimic the format of the tool. If I could get the Android app to at least try to parse my `.gls` files, I would probably manage debug the format fully

**Comment by jubalh** [comment]
@alastairdb which course do you try to parse?

**Comment by jubalh** [comment]
@alastairdb it's just a zip file containig a gsp file which is all the texts and then all the seperate mp3 files.

**Comment by alastairdb** [comment]
Thanks a lot for your extensive reply. I actually have an old Chinese course and the text in the PDFs is not immediately accessible. I used your audio splitter and it worked a treat! The text I had to drag out semi-automatically with Tesseract. For the time being, I have the course converted to Anki files. When I get time, I'll try your phone app again

**Comment by chickendude** [comment]
Ah yeah if you're using the older PDFs (that you couldn't copy/paste from) it's not going to work, it doesn't do OCR it just pulls the text from the PDF itself. You'd need to use the latest PDF they released for it to work. If you need help getting it set up, feel free to get in touch.

**Comment by afdlt** [comment]
Hey chickendude, thank you so much for creating this app and sharing it with everyone. Im struggling to figure out how to create the gls packs for my mandarin taiwan course. Do you or anyone else have mandarin gls packs already made that they wouldnt mind sharing with me? im just a dude thats not very technologically gifted (to say the least lol). If not, is there a simpler way to do it? Anything helps. Thank you!
