### ISSUE TITLE
Remove sentences one doesnt like

### ISSUE THREAD

**Issue by jubalh** [chickendude/Natibo#26]
I think the the new Glossika AI one can remove sentences one doesnt like from being displayed.

**Comment by chickendude** [comment]
This is definitely planned, i'm thinking more of an ignore feature so you could potentially unignore it as well, however there are a few complicated things like whether it should ignore the sentence for all of that language's courses or just that one.

**Comment by chickendude** [comment]
duplic

**Comment by chickendude** [comment]
Duplicate of #11.
