### ISSUE TITLE
Difficulty figuring out the gls pack 

### ISSUE THREAD

**Issue by afdlt** [chickendude/Natibo#38]
Hey chickendude! 
Im not very tech savvy but i've been looking for an app like the one you have made for a while now and i really want to try to figure this out. I dont understand how to create the gls packs from the mp3's and pdfs from my mandarin course. I have downloaded the GlossikaNativeGLS thing but have no idea what to do with it or what the heck im doing lol. I have read the language learner forumn a bunch and seen the explanations of what to do but it still doesnt make any sense to me. Is there a page with info that you think would give me more insight to all of this? Or perhaps you have gls packs for mandarin taiwan already made? Anything helps. Thank you for creating this btw!

**Comment by chickendude** [comment]
I was working on an online tool to help simplify the creation process, i took it offline as i changed the format of the gls files and never got around to updating the site, but i'd definitely like to improve the pack creation process as it's pretty inaccessible at the moment. If you want to reach out to me directly (my e-mail's listed in my Github profile page) I'll help walk you through the steps necessary to build the pack (or alternatively work on getting the online tool fixed).

**Comment by afdlt** [comment]
Thank you so much! I just sent over an email to you
