### ISSUE TITLE
manual GLS pack creation

### ISSUE THREAD

**Issue by russell359** [chickendude/Natibo#40]
Hi, I have the Taiwan Mandarin, Taiwanese Minnan, and Japanese mp3 language packs, I already manually split up the audio files and text which I used to create anki decks for my study purposes, just wondering if I could manually create the gls import pack or somewhere get these files into natibo?

**Comment by jubalh** [comment]
Not sure whether I understand the question right. But I used https://github.com/chickendude/GlossikaNativeGLS to split the packs. If you already did so you just need to transform it so its the same format. I guess the script will help you with determining that.
Or you just use the script on your files to create the gls pack.

**Comment by chickendude** [comment]
Yeah, the scripts are what i use to make the gls packs. However, some of the packs aren't as straightforward. I'm not sure if any of those three languages have been split before, so the repo might not be updated to handle them. Feel free to open an issue there (in the GlossikaNativeGLS repo) or shoot me an e-mail (my e-mail's on my profile page) and i'd be more than happy to help you set things up.
