### ISSUE TITLE
Add support for Assimil courses.

### ISSUE THREAD

**Issue by chickendude** [chickendude/Natibo#8]
Look into adding support for splitting and loading Assimil courses as well.

**Comment by jubalh** [comment]
What idea did you originally have here? And why discarded? :)

**Comment by chickendude** [comment]
Well i thought it would be nice to have Assimil courses be importable into the app, however they don't have a PDF version and there's also no base language audio so it wouldn't really work that well unless you recorded the base language audio yourself and then wrote out all the sentences as well. If someone wanted to do all that work it'd be possible to do, just make sure you save it in the write format, i'm just not sure i can make the tools to simplify that process very much.

**Comment by jubalh** [comment]
Okay
